// Build lua/strudel-types/sounds.lua: sound names, drum-machine banks, and preview
// URLs (first sample per name) from Strudel's sound registrations + prebaked maps.
//
// Usage: node emit-sounds.mjs <gm-names-file> <out.lua>
//   gm-names-file: gm_* names, one per line (grepped from packages/soundfonts/gm.mjs)
// Requires Node 18+ (global fetch).

import fs from 'node:fs';
import { pathToFileURL } from 'node:url';

const [, , gmPath, outPath] = process.argv;
if (!outPath) {
  console.error('usage: emit-sounds.mjs <gm.mjs path> <out.lua>');
  process.exit(1);
}

// Stable built-in synths (superdough registerSynthSounds + zzfx); no sample URL.
const SYNTHS = [
  'triangle', 'square', 'sawtooth', 'sine', 'user', 'one', 'tri', 'sqr', 'saw', 'sin',
  'sbd', 'supersaw', 'bytebeat', 'pulse', 'bus', 'pink', 'white', 'brown', 'crackle',
  'zzfx', 'z_sine', 'z_sawtooth', 'z_triangle', 'z_square', 'z_tan', 'z_noise',
];

// GM soundfonts: import packages/soundfonts/gm.mjs -> { gm_name: [preset, ...] }.
// Each gm_name maps to webaudiofont presets; preview uses the first one.
let gmObj = {};
if (gmPath && fs.existsSync(gmPath)) {
  try { gmObj = (await import(pathToFileURL(gmPath).href)).default || {}; }
  catch (e) { console.error('warn: could not import gm.mjs: ' + e.message); }
}
const gm = Object.keys(gmObj);
const soundfonts = {};
for (const name of gm) {
  const v = gmObj[name];
  if (Array.isArray(v) && typeof v[0] === 'string') soundfonts[name] = v[0];
}

const SAMPLE_MAPS = [
  'https://raw.githubusercontent.com/tidalcycles/Dirt-Samples/master/strudel.json',
  'https://strudel.b-cdn.net/piano.json',
  'https://strudel.b-cdn.net/vcsl.json',
  'https://strudel.b-cdn.net/uzu-drumkit.json',
  'https://strudel.b-cdn.net/uzu-wavetables.json',
  'https://strudel.b-cdn.net/mridangam.json',
];
const DRUM = 'https://strudel.b-cdn.net/tidal-drum-machines.json';
const DRUM_ALIAS = 'https://strudel.b-cdn.net/tidal-drum-machines-alias.json';

async function getJson(u) {
  try {
    const r = await fetch(u);
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}

// First sample file in a map value: a string, an array of files, or a pitched
// instrument object { note: file|files } (e.g. VCSL marimba). Recurses.
function firstFile(v) {
  if (typeof v === 'string') return v;
  if (Array.isArray(v)) {
    for (const x of v) { const f = firstFile(x); if (f) return f; }
    return null;
  }
  if (v && typeof v === 'object') {
    for (const k of Object.keys(v)) { const f = firstFile(v[k]); if (f) return f; }
  }
  return null;
}

const sampleKeys = new Set();
const urls = {};
for (const m of SAMPLE_MAPS) {
  const o = await getJson(m);
  if (!o) { console.error('warn: could not fetch ' + m); continue; }
  const base = o._base || '';
  for (const [k, v] of Object.entries(o)) {
    if (k === '_base') continue;
    sampleKeys.add(k);
    if (!urls[k]) {
      const f = firstFile(v);
      if (f) urls[k] = base + f; // first map wins
    }
  }
}

const banks = new Set();
const dm = await getJson(DRUM);
if (dm) for (const k of Object.keys(dm)) if (k !== '_base') banks.add(k.replace(/_[^_]*$/, ''));
const al = await getJson(DRUM_ALIAS);
if (al) for (const v of Object.values(al)) banks.add(v);

const sounds = [...new Set([...SYNTHS, ...gm, ...sampleKeys])].sort();
const banksArr = [...banks].sort();

const esc = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const tbl = (arr) => {
  const out = [];
  let line = '  ';
  for (const x of arr) {
    const t = esc(x) + ', ';
    if ((line + t).length > 100) { out.push(line.replace(/ $/, '')); line = '  '; }
    line += t;
  }
  if (line.trim()) out.push(line.replace(/ $/, ''));
  return out.join('\n');
};
const urlTbl = Object.keys(urls).sort().map((k) => `  [${esc(k)}] = ${esc(urls[k])},`).join('\n');
const sfTbl = Object.keys(soundfonts).sort().map((k) => `  [${esc(k)}] = ${esc(soundfonts[k])},`).join('\n');

fs.writeFileSync(outPath, `-- AUTO-GENERATED by strudel-types.nvim (scripts/gen-sounds.sh). Do not edit by hand.
-- ${sounds.length} sounds, ${banksArr.length} drum-machine banks, ${Object.keys(urls).length} sample URLs, ${Object.keys(soundfonts).length} soundfont presets.
return {
  sounds = {
${tbl(sounds)}
  },
  banks = {
${tbl(banksArr)}
  },
  -- name -> first sample URL (sample sounds; previewed directly)
  urls = {
${urlTbl}
  },
  -- gm_* name -> first webaudiofont preset (previewed via scripts/preview-soundfont.mjs)
  soundfonts = {
${sfTbl}
  },
}
`);
console.error(`emit-sounds: ${sounds.length} sounds, ${banksArr.length} banks, ${Object.keys(urls).length} urls, ${Object.keys(soundfonts).length} soundfonts`);
