#!/usr/bin/env bash
# Regenerate lua/strudel-types/sounds.lua: the list of Strudel sound names (synths +
# GM soundfonts + default sample maps) and drum-machine banks.
#
# Sources: synth names are stable (hardcoded); GM soundfonts come from the Strudel
# source (packages/soundfonts/gm.mjs); samples + drum machines come from the sample
# maps Strudel prebakes. Requires: git, curl, node, network.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/lua/strudel-types/sounds.lua"
REPO="${STRUDEL_REPO:-https://codeberg.org/uzu/strudel.git}"
CDN="${STRUDEL_CDN:-https://strudel.b-cdn.net}"
DIRT="${STRUDEL_DIRT:-https://raw.githubusercontent.com/tidalcycles/dirt-samples/master/strudel.json}"

for bin in git curl node; do
  command -v "$bin" >/dev/null || { echo "strudel-types: '$bin' is required" >&2; exit 1; }
done
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

# keys of a JSON sample-map (skip the _base url key) -> one per line
keys() { curl -fsSL "$1" 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{for(const k of Object.keys(JSON.parse(s)))if(k!=="_base")console.log(k)}catch(e){}})'; }

echo "strudel-types(sounds): synths..."
printf '%s\n' triangle square sawtooth sine user one tri sqr saw sin sbd supersaw \
  bytebeat pulse bus pink white brown crackle zzfx z_sine z_sawtooth z_triangle \
  z_square z_tan z_noise > "$WORK/sounds.txt"

echo "strudel-types(sounds): GM soundfonts (clone)..."
git clone --depth 1 "$REPO" "$WORK/src" >/dev/null 2>&1
grep -oE '^[[:space:]]+gm_[a-z0-9_]+:' "$WORK/src/packages/soundfonts/gm.mjs" | tr -d ': ' >> "$WORK/sounds.txt" || true

echo "strudel-types(sounds): sample maps..."
{ keys "$DIRT"; for m in piano vcsl uzu-drumkit uzu-wavetables mridangam; do keys "$CDN/$m.json"; done; } >> "$WORK/sounds.txt"

echo "strudel-types(sounds): drum machine banks..."
curl -fsSL "$CDN/tidal-drum-machines.json" 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const b=new Set();for(const k of Object.keys(JSON.parse(s)))if(k!=="_base")b.add(k.replace(/_[^_]*$/,""));for(const x of b)console.log(x)}catch(e){}})' > "$WORK/banks.txt"
curl -fsSL "$CDN/tidal-drum-machines-alias.json" 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{for(const v of Object.values(JSON.parse(s)))console.log(v)}catch(e){}})' >> "$WORK/banks.txt"

echo "strudel-types(sounds): emitting $OUT..."
node -e '
const fs=require("fs");
const uniq=p=>[...new Set(fs.readFileSync(p,"utf8").split("\n").map(s=>s.trim()).filter(Boolean))].sort();
const sounds=uniq(process.argv[1]), banks=uniq(process.argv[2]);
const esc=s=>"\x27"+s.replace(/\x27/g,"\\\x27")+"\x27";
const tbl=a=>{let o=[],l="  ";for(const x of a){const t=esc(x)+", ";if((l+t).length>96){o.push(l.replace(/ $/,""));l="  ";}l+=t;}if(l.trim())o.push(l.replace(/ $/,""));return o.join("\n");};
fs.writeFileSync(process.argv[3], `-- AUTO-GENERATED by strudel-types.nvim (scripts/gen-sounds.sh). Do not edit by hand.
-- ${sounds.length} playable sound names (synths + GM soundfonts + default samples) and
-- ${banks.length} drum-machine banks.
return {
  sounds = {
${tbl(sounds)}
  },
  banks = {
${tbl(banks)}
  },
}
`);
console.log("sounds: "+sounds.length+", banks: "+banks.length);
' "$WORK/sounds.txt" "$WORK/banks.txt" "$OUT"
echo "strudel-types(sounds): done -> $OUT"
